openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0

servers:
  - url: https://79ngk4sfs8.execute-api.eu-west-1.amazonaws.com/dev/products
    description: Dev environment

paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Could not load products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/{id}:
    get:
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
        - description
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string